[U] Migrate vue-cli to Vite
hykilpikonna/OneAmongUs.Web pull request #3
Opened 2022-03-11 17:37 UTC by Mak1o

[Vite](https://vitejs.dev/) is the next-generation frontend toolchain by Vue team, aiming at replacing `vue-cli`.

Bundle size: **46 MiB** → **39 MiB**
Build time (w/o `vue-tsc`): **11.85s** → **4.03s**
Preview time: **~4.5s** → **160ms**

2022-03-11 17:43 UTC, hykilpikonna commented
谢谢!

2022-03-11 17:46 UTC, hykilpikonna requested changes

2022-03-11 17:46 UTC, hykilpikonna commented on src/components/Markdown.vue
> +    <div id="Markdown" class="markdown-content" :style="margins ? {margin: '10px min(4vw, 40px)'} : {}" v-html="html" />
这里不能用 v-html 啦，因为 v-html 不能解析 Vue Component
（显示照片堆的那个 PhotoScroll 是用动态解析 Vue Component 实现的）

2022-03-11 17:49 UTC, Mak1o commented on src/components/Markdown.vue
> +    <div id="Markdown" class="markdown-content" :style="margins ? {margin: '10px min(4vw, 40px)'} : {}" v-html="html" />
感觉用 Dynamic 来展示动态内容似乎并不是一个很好的实践，我再去看一下

2022-03-11 18:09 UTC, Mak1o commented on src/components/Markdown.vue
> +    <div id="Markdown" class="markdown-content" :style="margins ? {margin: '10px min(4vw, 40px)'} : {}" v-html="html" />
可能更好的解决方案是设计一种结构化的格式，在其中放置一些 placeholder 用来在渲染时替换为各种预定义的组件 ……？

不过比较复杂，现在这样也可以。

2022-03-11 18:34 UTC, hykilpikonna commented on src/components/Markdown.vue
> +    <div id="Markdown" class="markdown-content" :style="margins ? {margin: '10px min(4vw, 40px)'} : {}" v-html="html" />
好神奇... 之前一直想把这个改掉是因为 runtimeCompiler 好像很大的样子（在 `vue.config.js` 里面把 `runtimeCompiler: true` 去掉的话可以剩下 1MB），不知道为什么换了 Vite 之后即使没有 runtimeCompiler 也能动态解析 Vue template

2022-03-11 18:39 UTC, merged

2022-03-12 01:20 UTC, Mak1o commented on src/components/Markdown.vue
> +    <div id="Markdown" class="markdown-content" :style="margins ? {margin: '10px min(4vw, 40px)'} : {}" v-html="html" />
https://github.com/hykilpikonna/OneAmongUs.Web/blob/554b15e41ce7dd2d67e6d9607efb68c5daae266d/vite.config.ts#L34

我这里通过 `resolve.alias` 设置了引入带 compiler 的 vue 版本，默认的话它引入的是 `vue.runtime.esm-bundler.js` 也就是不带 compiler 只带 runtime 的版本

2022-03-12 01:30 UTC, Mak1o commented on src/components/Markdown.vue
> +    <div id="Markdown" class="markdown-content" :style="margins ? {margin: '10px min(4vw, 40px)'} : {}" v-html="html" />
https://mdxjs.com/

我昨晚竟然忘记了 MDX 这个东西，醒来才想起来
要不要试试 qwq

2022-03-12 04:08 UTC, Mak1o commented on src/components/Markdown.vue
> +    <div id="Markdown" class="markdown-content" :style="margins ? {margin: '10px min(4vw, 40px)'} : {}" v-html="html" />
MDX 的好处就是，它可以在服务器端编译好，直接返回 js 代码在前端执行，前端没有额外的开销，特别适合这种比较静态的内容站